Documentation Updates
Azure/RAI-vNext-Preview pull request #64
Opened 2022-04-29 13:54 UTC by riedgar-ms

Various changes to the documentation:

- Make sure need for MiniConda is clear
- Remove old instructions about SDKv2.1.2
- Tweak some language

2022-05-02 14:09 UTC, riedgar-ms commented
Some further questions for @minthigpen :

- The contents of `docs/PythonSDK` are rather out-of-date now. However, is it worth updating them given that we have a working notebook?
- Do we still want `setup.md` at all?

2022-05-03 20:15 UTC, minthigpen requested changes

2022-05-03 20:15 UTC, minthigpen commented on README.md
>  ### Generating Responsibleai AI Dashboard insights
"Responsibleai" should be just "Responsible"

2022-05-04 16:01 UTC, riedgar-ms commented
@minthigpen , can you validate the change, please?

2022-05-06 16:53 UTC, merged